# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/eoan64"
  config.ssh.insert_key = false
  config.vm.network "private_network", ip: "192.168.100.10"
  config.vm.provision :shell do |s|
    s.path = "init.sh"
    s.args   = "master" 
  end
  config.vm.provider "virtualbox" do |vm|
    vm.memory = 2048
  end
end
